--
-- Table structure for table digglike_default_message
--
ALTER TABLE digglike_default_message  ADD COLUMN notification_new_comment_title long varchar;
ALTER TABLE digglike_default_message  ADD COLUMN notification_new_comment_body long varchar;
ALTER TABLE digglike_default_message  ADD COLUMN notification_new_digg_submit_title long varchar;
ALTER TABLE digglike_default_message  ADD COLUMN notification_new_digg_submit_body long varchar;

ALTER TABLE digglike_digg ADD COLUMN notification_new_comment_sender varchar(255);
ALTER TABLE digglike_digg ADD COLUMN notification_new_comment_title long varchar;
ALTER TABLE digglike_digg ADD COLUMN notification_new_comment_body long varchar;
ALTER TABLE digglike_digg ADD COLUMN notification_new_digg_submit_sender varchar(255);
ALTER TABLE digglike_digg ADD COLUMN notification_new_digg_submit_title long varchar;
ALTER TABLE digglike_digg ADD COLUMN notification_new_digg_submit_body long varchar;

UPDATE digglike_default_message  set notification_new_comment_title = '#i18n{digglike.notifications.newComment.title}', notification_new_comment_body='<html>\r\n	<head>\r\n		<link href="${base_url}css/bootstrap.min.css" rel="stylesheet"/>\r\n	</head>\r\n	<body>\r\n		<p>#i18n{digglike.notifications.newComment.hello}</p>\r\n		<br />\r\n		${comments?size} #i18n{digglike.notifications.newComment.newCommentsPosted} :\r\n		<br />\r\n		<#list comments as comment_submit>\r\n			<p>\r\n				<#if comment_submit.isOfficialAnswer()>\r\n					<span class="badge badge-warning">\r\n						<i class="icon-star icon-white"></i> \r\n						#i18n{digglike.manageCommentSubmit.officialAnswer}\r\n					</span>\r\n					&nbsp;\r\n				</#if>\r\n				<i class="icon-calendar"></i> ${comment_submit.dateComment?string("dd/MM/yyyy HH:mm:ss")}\r\n			</p>\r\n			<#if comment_submit.value?length &gt; 100>\r\n				${comment_submit.value?substring(0,100)}\r\n			<#else>\r\n				${comment_submit.value}\r\n			</#if>\r\n			<a class="btn btn-small btn-primary" href="${base_url}/jsp/site/Portal.jsp?page=digg&id_digg=${comment_submit.diggSubmit.digg.idDigg}&id_digg_submit=${comment_submit.diggSubmit.idDiggSubmit}&action=view_digg_submit">\r\n				#i18n{digglike.diggListSubmit.labelReadMore}\r\n			</a>\r\n			<br />\r\n			<br />\r\n		</#list>\r\n	</body>\r\n</html>', notification_new_digg_submit_title='#i18n{digglike.notifications.newDiggSubmit.title}', notification_new_digg_submit_body='<html>\r\n	<head>\r\n		<link href="${base_url}css/bootstrap.min.css" rel="stylesheet"/>\r\n	</head>\r\n	<body>\r\n		<p>#i18n{digglike.notifications.newDiggSubmit.hello}</p>\r\n		<br />\r\n		${diggSubmits?size} #i18n{digglike.notifications.newDiggSubmit.newDiggSubmitPosted} :\r\n		<br />\r\n		<#list diggSubmits as diggSubmit>\r\n			<p>\r\n				${diggSubmit.diggSubmitTitle}\r\n			</p>\r\n			<a class="btn btn-small btn-primary" href="${base_url}/jsp/site/Portal.jsp?page=digg&id_digg=${diggSubmit.digg.idDigg}&id_digg_submit=${diggSubmit.idDiggSubmit}&action=view_digg_submit">\r\n				#i18n{digglike.diggListSubmit.labelReadMore}\r\n			</a>\r\n			<br />\r\n			<br />\r\n		</#list>\r\n	</body>\r\n</html>';
UPDATE digglike_digg  set notification_new_comment_title = '#i18n{digglike.notifications.newComment.title}', notification_new_comment_body='<html>\r\n	<head>\r\n		<link href="${base_url}css/bootstrap.min.css" rel="stylesheet"/>\r\n	</head>\r\n	<body>\r\n		<p>#i18n{digglike.notifications.newComment.hello}</p>\r\n		<br />\r\n		${comments?size} #i18n{digglike.notifications.newComment.newCommentsPosted} :\r\n		<br />\r\n		<#list comments as comment_submit>\r\n			<p>\r\n				<#if comment_submit.isOfficialAnswer()>\r\n					<span class="badge badge-warning">\r\n						<i class="icon-star icon-white"></i> \r\n						#i18n{digglike.manageCommentSubmit.officialAnswer}\r\n					</span>\r\n					&nbsp;\r\n				</#if>\r\n				<i class="icon-calendar"></i> ${comment_submit.dateComment?string("dd/MM/yyyy HH:mm:ss")}\r\n			</p>\r\n			<#if comment_submit.value?length &gt; 100>\r\n				${comment_submit.value?substring(0,100)}\r\n			<#else>\r\n				${comment_submit.value}\r\n			</#if>\r\n			<a class="btn btn-small btn-primary" href="${base_url}/jsp/site/Portal.jsp?page=digg&id_digg=${comment_submit.diggSubmit.digg.idDigg}&id_digg_submit=${comment_submit.diggSubmit.idDiggSubmit}&action=view_digg_submit">\r\n				#i18n{digglike.diggListSubmit.labelReadMore}\r\n			</a>\r\n			<br />\r\n			<br />\r\n		</#list>\r\n	</body>\r\n</html>', notification_new_digg_submit_title='#i18n{digglike.notifications.newDiggSubmit.title}', notification_new_digg_submit_body='<html>\r\n	<head>\r\n		<link href="${base_url}css/bootstrap.min.css" rel="stylesheet"/>\r\n	</head>\r\n	<body>\r\n		<p>#i18n{digglike.notifications.newDiggSubmit.hello}</p>\r\n		<br />\r\n		${diggSubmits?size} #i18n{digglike.notifications.newDiggSubmit.newDiggSubmitPosted} :\r\n		<br />\r\n		<#list diggSubmits as diggSubmit>\r\n			<p>\r\n				${diggSubmit.diggSubmitTitle}\r\n			</p>\r\n			<a class="btn btn-small btn-primary" href="${base_url}/jsp/site/Portal.jsp?page=digg&id_digg=${diggSubmit.digg.idDigg}&id_digg_submit=${diggSubmit.idDiggSubmit}&action=view_digg_submit">\r\n				#i18n{digglike.diggListSubmit.labelReadMore}\r\n			</a>\r\n			<br />\r\n			<br />\r\n		</#list>\r\n	</body>\r\n</html>';


