--
-- Table structure for table suggest_default_message
--
ALTER TABLE suggest_default_message  ADD COLUMN notification_new_comment_title long varchar;
ALTER TABLE suggest_default_message  ADD COLUMN notification_new_comment_body long varchar;
ALTER TABLE suggest_default_message  ADD COLUMN notification_new_suggest_submit_title long varchar;
ALTER TABLE suggest_default_message  ADD COLUMN notification_new_suggest_submit_body long varchar;

ALTER TABLE suggest_suggest ADD COLUMN notification_new_comment_sender varchar(255);
ALTER TABLE suggest_suggest ADD COLUMN notification_new_comment_title long varchar;
ALTER TABLE suggest_suggest ADD COLUMN notification_new_comment_body long varchar;
ALTER TABLE suggest_suggest ADD COLUMN notification_new_suggest_submit_sender varchar(255);
ALTER TABLE suggest_suggest ADD COLUMN notification_new_suggest_submit_title long varchar;
ALTER TABLE suggest_suggest ADD COLUMN notification_new_suggest_submit_body long varchar;

UPDATE suggest_default_message  set notification_new_comment_title = '#i18n{suggest.notifications.newComment.title}', notification_new_comment_body='<html>\r\n	<head>\r\n		<link href="${base_url}css/bootstrap.min.css" rel="stylesheet"/>\r\n	</head>\r\n	<body>\r\n		<p>#i18n{suggest.notifications.newComment.hello}</p>\r\n		<br />\r\n		${comments?size} #i18n{suggest.notifications.newComment.newCommentsPosted} :\r\n		<br />\r\n		<#list comments as comment_submit>\r\n			<p>\r\n				<#if comment_submit.isOfficialAnswer()>\r\n					<span class="badge badge-warning">\r\n						<i class="icon-star icon-white"></i> \r\n						#i18n{suggest.manageCommentSubmit.officialAnswer}\r\n					</span>\r\n					&nbsp;\r\n				</#if>\r\n				<i class="icon-calendar"></i> ${comment_submit.dateComment?string("dd/MM/yyyy HH:mm:ss")}\r\n			</p>\r\n			<#if comment_submit.value?length &gt; 100>\r\n				${comment_submit.value?substring(0,100)}\r\n			<#else>\r\n				${comment_submit.value}\r\n			</#if>\r\n			<a class="btn btn-small btn-primary" href="${base_url}/jsp/site/Portal.jsp?page=suggest&id_suggest=${comment_submit.suggestSubmit.suggest.idSuggest}&id_suggest_submit=${comment_submit.suggestSubmit.idSuggestSubmit}&action=view_suggest_submit">\r\n				#i18n{suggest.suggestListSubmit.labelReadMore}\r\n			</a>\r\n			<br />\r\n			<br />\r\n		</#list>\r\n	</body>\r\n</html>', notification_new_suggest_submit_title='#i18n{suggest.notifications.newSuggestSubmit.title}', notification_new_suggest_submit_body='<html>\r\n	<head>\r\n		<link href="${base_url}css/bootstrap.min.css" rel="stylesheet"/>\r\n	</head>\r\n	<body>\r\n		<p>#i18n{suggest.notifications.newSuggestSubmit.hello}</p>\r\n		<br />\r\n		${suggestSubmits?size} #i18n{suggest.notifications.newSuggestSubmit.newSuggestSubmitPosted} :\r\n		<br />\r\n		<#list suggestSubmits as suggestSubmit>\r\n			<p>\r\n				${suggestSubmit.suggestSubmitTitle}\r\n			</p>\r\n			<a class="btn btn-small btn-primary" href="${base_url}/jsp/site/Portal.jsp?page=suggest&id_suggest=${suggestSubmit.suggest.idSuggest}&id_suggest_submit=${suggestSubmit.idSuggestSubmit}&action=view_suggest_submit">\r\n				#i18n{suggest.suggestListSubmit.labelReadMore}\r\n			</a>\r\n			<br />\r\n			<br />\r\n		</#list>\r\n	</body>\r\n</html>';
UPDATE suggest_suggest  set notification_new_comment_title = '#i18n{suggest.notifications.newComment.title}', notification_new_comment_body='<html>\r\n	<head>\r\n		<link href="${base_url}css/bootstrap.min.css" rel="stylesheet"/>\r\n	</head>\r\n	<body>\r\n		<p>#i18n{suggest.notifications.newComment.hello}</p>\r\n		<br />\r\n		${comments?size} #i18n{suggest.notifications.newComment.newCommentsPosted} :\r\n		<br />\r\n		<#list comments as comment_submit>\r\n			<p>\r\n				<#if comment_submit.isOfficialAnswer()>\r\n					<span class="badge badge-warning">\r\n						<i class="icon-star icon-white"></i> \r\n						#i18n{suggest.manageCommentSubmit.officialAnswer}\r\n					</span>\r\n					&nbsp;\r\n				</#if>\r\n				<i class="icon-calendar"></i> ${comment_submit.dateComment?string("dd/MM/yyyy HH:mm:ss")}\r\n			</p>\r\n			<#if comment_submit.value?length &gt; 100>\r\n				${comment_submit.value?substring(0,100)}\r\n			<#else>\r\n				${comment_submit.value}\r\n			</#if>\r\n			<a class="btn btn-small btn-primary" href="${base_url}/jsp/site/Portal.jsp?page=suggest&id_suggest=${comment_submit.suggestSubmit.suggest.idSuggest}&id_suggest_submit=${comment_submit.suggestSubmit.idSuggestSubmit}&action=view_suggest_submit">\r\n				#i18n{suggest.suggestListSubmit.labelReadMore}\r\n			</a>\r\n			<br />\r\n			<br />\r\n		</#list>\r\n	</body>\r\n</html>', notification_new_suggest_submit_title='#i18n{suggest.notifications.newSuggestSubmit.title}', notification_new_suggest_submit_body='<html>\r\n	<head>\r\n		<link href="${base_url}css/bootstrap.min.css" rel="stylesheet"/>\r\n	</head>\r\n	<body>\r\n		<p>#i18n{suggest.notifications.newSuggestSubmit.hello}</p>\r\n		<br />\r\n		${suggestSubmits?size} #i18n{suggest.notifications.newSuggestSubmit.newSuggestSubmitPosted} :\r\n		<br />\r\n		<#list suggestSubmits as suggestSubmit>\r\n			<p>\r\n				${suggestSubmit.suggestSubmitTitle}\r\n			</p>\r\n			<a class="btn btn-small btn-primary" href="${base_url}/jsp/site/Portal.jsp?page=suggest&id_suggest=${suggestSubmit.suggest.idSuggest}&id_suggest_submit=${suggestSubmit.idSuggestSubmit}&action=view_suggest_submit">\r\n				#i18n{suggest.suggestListSubmit.labelReadMore}\r\n			</a>\r\n			<br />\r\n			<br />\r\n		</#list>\r\n	</body>\r\n</html>';


